# Generated by Django 5.0.6 on 2024-10-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Immobilier ", "Immobilier "),
                            ("Véhicules", "Véhicules"),
                            ("Équipement de maison", "Équipement de maison"),
                            ("Événements et loisirs", "Événements et loisirs"),
                            ("Instruments de musique", "Instruments de musique"),
                            ("Matériel de voyage", "Matériel de voyage"),
                            ("Mode et accessoires", "Mode et accessoires"),
                            (
                                "Électronique et Multimédia",
                                "Électronique et Multimédia",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("photo", models.ImageField(upload_to="biens/")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("disponibilite", models.BooleanField(default=True)),
                ("date_debut_disponibilite", models.DateField()),
                ("date_fin_disponibilite", models.DateField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
