# Generated by Django 5.0.6 on 2024-09-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_delete_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
