# Generated by Django 5.0.6 on 2024-10-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("en_attente", "En attente"), ("paye", "Payé")],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
