# Generated by Django 5.0.6 on 2024-10-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
    ]
