# Generated by Django 5.0.6 on 2024-10-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_remove_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="date_paiement",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
