# Generated by Django 5.0.6 on 2024-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_utilisateur", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="telephone",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="city",
            new_name="ville",
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
